name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Generate and Build with CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sunshine-Toolbox_msvc_64
          path: build/Release/Sunshine-Toolbox.exe
